#!/usr/bin/env sh
# update db if new emoji
# frece update "fruits.db" "fruits.txt" --purge-old

EMOJI_FILE="$HOME/.local/bin/scripts/static/emoji"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/frece"
DB_FILE="$DATA_DIR/emoji.db"

[[ ! -f $DB_FILE ]] &&  frece init "$DB_FILE" "$EMOJI_FILE" && notify-send "db init"

# frece print order by frequence
chosen=$(frece print "$DB_FILE" | rofi -dmenu -i -p "$1")

[[ -z $chosen ]] && exit 1

frece increment "$DB_FILE" "$chosen"

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xsel -b
notify-send "'$c' copied to clipboard." &

# s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
# echo "$s" | tr -d '\n' | xclip
# notify-send "'$s' copied to primary." &

