#!/bin/sh

result=$(ps ax|grep -v grep|grep picom)

if [ -z "$result" ]; then
  eval "picom --config "${XDG_CONFIG_HOME:-$HOME/.config}/picom_blur.conf" -b --experimental-backends"
  # eval "picom -b"    # corner-radius 
  bspc config border_width         0
  notify-send "compositor on" &
else
  eval "killall picom"
  bspc config border_width         5
  notify-send "compositor off" &
fi
