#!/bin/sh

# ~/.local/bin/scripts/dwm/dwm-status.sh &
~/.local/bin/scripts/wp-autochange &
~/.local/bin/scripts/alpha-toggle &

unclutter &
# dunst &
# ~/.local/bin/scripts/run-mailsync.sh &
~/.local/bin/scripts/autostart_wait &
~/.local/bin/scripts/tap-to-click.sh &
pulseaudio --start --use-pid-file=true &



