#!/bin/sh

sleep 2
nm-applet &
fcitx5 -d &
flameshot &
# nutstore &
cfw &  # clash for windows
# clash-verge & # clash verge
nextcloud &
xrandr --output HDMI-0 --scale 1.3x1.3 && ~/.local/bin/scripts/wp-change

