#!/bin/sh

# feh --recursive --randomize --bg-fill --no-fehbg ~/Pictures/wallpapers/macOS
feh --recursive --randomize --bg-fill --no-fehbg /home/ring/opt/Pictures/wallpapers/JOJO/wallhaven-gjj5kd.png
