#!/usr/bin/bash
pids=$(xdotool search --class scratchpad)
TERMINAL=${TERMINAL:-"st"}

if [ -z "$pids" ]; then
  case "$TERMINAL" in
	"st") 
	  eval "st -c scratchpad -t scratchpad -g 130x40" ;;
	"alacritty") 
	  eval "alacritty --class scratchpad,scratchpad -d 130 045"
  esac
else
  for pid in $pids; do
  	bspc node $pid --flag hidden -f
    bspc node $pid -m pointed
  done
fi

