#!/usr/bin/bash
pids=$(xdotool search --classname scratchpad)
TERMINAL=${TERMINAL:-"st"}

if [ -z "$pids" ]; then
  case "$TERMINAL" in
	"st") 
	  # eval "st -c scratchpad -t scratchpad -g 160x60" ;;
	  eval "tabbed -c -p s+1 -g 1800x1300 -n \"scratchpad\" -r 2 st -w '' " ;;
	"alacritty") 
	  eval "alacritty --class scratchpad,scratchpad"
  esac
else
  for pid in $pids; do
  	bspc node $pid --flag hidden -f
    bspc node $pid -m pointed
  done
fi

