#!/usr/bin/env sh

EXCLUSIVE_ID=$(echo "obase=16; $(xdotool search --class scratchpad)" | bc)
NODE_ID=($(bspc query -N -n .local.window.\!sticky.hidden))
NODE_ID+=($(bspc query -N -n .local.window.sticky.hidden.above | grep -v "$EXCLUSIVE_ID"))
NODE_ID+=($(bspc query -N -n .local.window.\!sticky.hidden.below))
INDEX=0
ENTRY=()

if [ -z "$NODE_ID" ]; then
    notify-send "👻 Nothing is hidden." "Catch you later XD"
    exit
fi

for node in ${NODE_ID[@]}; do
  ENTRY+=("$INDEX $(xdotool getwindowname $node)")
  ((INDEX++))
done

chosen=$(printf '%s\n' "${ENTRY[@]}" | rofi -p "Unhide:" -dmenu -i | awk '{ print $1 }')

[ -n "$chosen" ] || exit

bspc node ${NODE_ID[$chosen]} -g hidden=off

